# config.example.yaml
# 此文件提供了配置文件的模板。请根据实际情况填写或修改以下配置项。

# 课程名称
course_name: "课程名称"

# 作业名称
assignment_name: "作业名称"

# 存放电子邮件文件的目录
email_dir: "data/emails"

# 输出目录，用于存放处理后的文件
output_dir: "output/"

# 处理过的邮件记录文件路径
processed_log_path: "output/processed_emails.json"

# 点名册配置
roster_config:
  # 点名册文件路径
  path: "data/点名册.xlsx"
  
  # 学生ID所在的列（Excel列的字母表示）
  student_id_column: "B"
  
  # 学生姓名所在的列
  name_column: "C"
  
  # 点名册开始读取的行号
  start_row: 6
